### ISSUE TITLE
Suggestion: Living and working should lower stamina

### ISSUE THREAD

**Issue by DcNdrew** [Sparkierkan7/realistic_stamina_mod#4]
Hi!
You can't run up and down, but you can chop down a forest. :D I think Energy should be lowered by living, mostly by working. :)

**Comment by Sparkierkan7** [comment]
I will probably make block breaking lower your stamina. But just living lowering your energy would make the game way too hard.

**Comment by DcNdrew** [comment]
I changed max stamina to 256, because that's better. 64 is too low in my opinion. With lowering energy for living isn't a bad thing with a good settings of stamina I think. No to mention that I use Psychedelicraft and if Sollace would make an option for how fast should sleep deprivation rise, I could synchronize with Energy.

**Comment by Sparkierkan7** [comment]
I guess i could make a config option for this.
